### ISSUE TITLE
How to implement multiple clusters

### ISSUE THREAD

**Issue by robp2175** [digitalocean/ceph_exporter#114]
If this need to go somewhere else I apologize; please point me in the correct direction.

I have two ceph clusters, both config files are in /etc/ceph and they are name ceph.conf and ceph2.conf.  However, I am unable to find documentation regarding what else I may have to do to send prometheus information on both clusters. Both config files do appear in the container. Any help would be appreciated.

**Comment by neurodrone** [comment]
Currently ceph-exporter is designed to talk to and extract metrics out of a single cluster. So if you have multiple Ceph clusters, you would need an instance of ceph-exporter for each of those. You can still scrape multiple such exporters from same prometheus and categorize them separately using labeling. 

This discussion might be helpful to you: https://github.com/digitalocean/ceph_exporter/issues/105.

**Comment by alram** [comment]
Support was added a while back https://github.com/digitalocean/ceph_exporter/commit/f67a9a0f7fdb0bc8a0da49ae12094752526d6746 but we never ended up using so some testing on your side might be required.

Here's an example of how you'd configure it:
```
cluster:
   - cluster_label: block01
     user: admin
     config_file: /etc/ceph/ceph.conf

   - cluster_label: block02
     user: admin
     config_file: /etc/ceph/ceph2.conf
```
