### ISSUE TITLE
Cannot connect to ceph cluster: permission denied

### ISSUE THREAD

**Issue by yeya24** [digitalocean/ceph_exporter#212]
Got the erorr from ceph exporter:

```
2022/03/26 23:11:54 cannot connect to ceph cluster: rados: Permission denied
```

Configuration file 

```
cat /etc/ceph/ceph.conf
[global]
mon_host = 172.18.146.132:6789,172.18.12.245:6789,172.18.83.88:6789

[client.admin]
keyring = /etc/ceph/ceph.client.admin.keyring
```

```
cat /etc/ceph/ceph.client.admin.keyring
[client.admin]
key = AQCNX4pf4T1RLBAA3jJF/Bhc0VcZ9BmGSIKtFA==
```

I am trying to set up ceph exporter with my rook ceph environment. Can I know how to get the exporter working using existing secrets from rook ceph?

**Comment by baergj** [comment]
At a glance that looks correct. Some things to try:
1. Is there a newline at the end of the keyring file? IIRC there are issues with parsing keyrings that don't have a newline (or any other character) after the key.
2. Have you tried not specifying the ports for mon_host?
3. Can you try adding the fsid to the ceph configuration file?

**Comment by youzi1030** [comment]
Is this problem solved, I have the same problem

```
version: '2'
services:
  ceph-exporter:
    container_name: ceph-exporter
    restart: always
    image: digitalocean/ceph_exporter
    volumes:
      - /etc/ceph:/etc/ceph
    ports:
      - '9128:9128'
```
