### ISSUE TITLE
IO metrics are 0

### ISSUE THREAD

**Issue by osx314** [digitalocean/ceph_exporter#83]
We have Ceph Luminous cluster running on Ubuntu 16.04.3 LTS. We also use ceph_exporter via docker (6 days old), but *_io_* metrics are always giving zero values. 
Any advice how to solve this?

Thank you

```
ceph_cache_evict_io_bytes{cluster="ceph"} 0
ceph_cache_flush_io_bytes{cluster="ceph"} 0
ceph_cache_promote_io_ops{cluster="ceph"} 0
ceph_client_io_ops{cluster="ceph"} 0
ceph_client_io_read_bytes{cluster="ceph"} 0
ceph_client_io_read_ops{cluster="ceph"} 0
ceph_client_io_write_bytes{cluster="ceph"} 0
ceph_client_io_write_ops{cluster="ceph"} 0
ceph_recovery_io_bytes{cluster="ceph"} 0
ceph_recovery_io_keys{cluster="ceph"} 0
ceph_recovery_io_objects{cluster="ceph"} 0
```

```
ceph11 ~ # ceph --version
ceph version 12.2.2 (cf0baeeeeba3b47f9427c6c97e2144b094b7e5ba) luminous (stable)


ceph11 ~ # ceph -s
  cluster:
    id:     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum ceph11,ceph12,ceph13
    mgr: ceph12(active), standbys: ceph13, ceph11
    osd: 28 osds: 28 up, 28 in
    rgw: 3 daemons active
 
  data:
    pools:   6 pools, 1064 pgs
    objects: 60452k objects, 6684 GB
    usage:   23480 GB used, 16565 GB / 40045 GB avail
    pgs:     1062 active+clean
             2    active+clean+scrubbing+deep
 
  io:
    client:   231 kB/s rd, 4014 kB/s wr, 243 op/s rd, 393 op/s wr
 
ceph11 ~ #
```
